# Starter pipeline
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Microsoft Azure Internal Consumption(5c056c10-4241-46ef-b0fa-50fdff97a5ec)'
    azureResourceGroup: 'myapp-rg'
    kubernetesCluster: 'myapp'
    command: 
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
